### spring配置
spring:
  ## 数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.79.149.40:3306/timo?useSSL=false&characterEncoding=utf-8
    username: root
    password: everything@123456Qwqe